### ISSUE TITLE
different results with v0.3

### ISSUE THREAD

**Issue by ijulca** [millanek/Dsuite#12]
I used Dsuite Dinvestigate from the version v0.1 and now I'm redoing my analysis with the new version, but I don't get the same results. I don't get the same number of windows and the positions of the windows are also different. I am using exactly the same dataset. What is the difference between the two versions? and why are the results different?

**Comment by millanek** [comment]
Hi 

Sorry for taking long to reply. This lockdown was a bit overwhelming, with homeschooling my son, and having a deadline for a big review article. So I wasn't paying attention here.

Here is your reply:
In short, the difference is that the initial version (in v0.1) counted the widow-size using any SNPs for the trio, whereas the newer implementation counts only SNPs which contribute to the results. Not all SNPs in the trio contribute meaningfully to the gene-flow estimates, only some SNPs do.

I suggest you use the newer versions, from v0.2 r15 onwards (and best please just use the latest version). You will need to decrease the window size in SNPs to get approximately equivalent physical window sizes you were getting in v0.1.

Best wishes
Milan

**Comment by ijulca** [comment]
Don't worry. Everybody is being affected by the covid situation. Thank you for your answer. I will use the new version.
