### ISSUE TITLE
Error parsing tree when using Fbranch

### ISSUE THREAD

**Issue by cbrock2** [millanek/Dsuite#13]
Hi,

I am getting the following error when running the Fbranch command:

##command
Build/Dsuite Fbranch kivu_tree kivu_list_dsuite_Fbkivu_tree.txt > fbranch.txt

##error
ERROR: The tree string could not be parsed correctly! The remaining unparsed tree string is:
((((((A.elegans,(P.graueri,EdwardSpecies)),((((Y.kamiranzovu,(P.paucidens,Micro)),(N.olivaceous,internalNode0X)),Lit_lig_red),(L.occultidens,M.crebidens))),P.vittatus),A.aeneocolor),(P.nyereri,H.squamipinnis)),A.alluaudi);

I am using the exact same tree in newick format I used to run Dtrios and the kivu_list_dsuite_Fbkivu_tree.txt output file does have f_G values. So the tree seems to work when setting up the possible calculations, but fails in this step.

I have tried removing the outgroup, or even running a small subset of the tree but I continue to get the same parsing error. 

Any ideas on what I can try? Thanks so much for the terrific package.

Best

Chad

**Comment by cbrock2** [comment]
Nevermind, I figured it out

**Comment by mrml500** [comment]
Hi Chad,
I'm having exactly the same issue, but haven't worked out the source of the problem. Do you remember how you fixed this?

All the best,
Mike

**Comment by josh3397** [comment]
> Nevermind, I figured it out

Hi Chad, Can you please tell how you figured it out, I'm also having the same issue.
