### ISSUE TITLE
How does it treat heterozygous sites?

### ISSUE THREAD

**Issue by Hinox47** [millanek/Dsuite#14]
I haven't found any comment about that. Thanks.

**Comment by millanek** [comment]
Hello

The logic for treating a heterozygous site is simple: one individual has two alleles. So if there is only one individual who is heterozygous, the the allele frequencies of both alleles are 0.5 
If the individual is homozygous then the allele frequencies are 0 for one allele and 1 for the other.

If there are two individuals, one is homozygous for an allele, and the other one is a het, then the allele frequency of that allele is 0.75. 

Hope this clarifies it
Milan
