### ISSUE TITLE
Tree file creates an error

### ISSUE THREAD

**Issue by MarineBio5** [millanek/Dsuite#15]
Hi Milan, 

Thanks for creating this program. I'm having a problem when I try and use a tree file. I see a previous issue with the same error message (fixed by ensuring species names in the map file and tree file are the same) but no matter what variants on species names or tree file I try I get the same error. Could there be another reason causing this?

The error is:
`There are 8 sets (excluding the Outgroup)
Going to calculate D and f4-ratio values for 56 trios
Out of Range error: map::at
species[i]: Species1
`
My tree file is:
`(Outgroup,((Species1(Species2)),(Species4(Species5,Species6,Species8,Species7,Species3))));`

And finally my map file is (formatted in two columns but with tab spacing - I think it displays differently here):
bb29	Species1
bb30	Species1
tpl40	Species2
t15	Species2
sbre460	Outgroup
sbre116871wga	Outgroup
lh802	xxx
lh806	xxx
S303	xxx
S304	xxx
WNAC11	Species3
WNAC14	Species3
WNAC16	Species3
WNAC19	Species3
WNAC8	Species3
wnac25	Species3
WNAP7	Species4
WNAP8	Species4
WNAP9	Species4
AZ108	Species5
AZ109	Species5
AZ2	Species5
AZ3	Species5
AZ40	Species5
AZ41	Species5
43GE	Species6
T19	Species6
19G	Species6
36GPC	Species6
37GPC	Species6
BS10	Species7
BS11	Species7
BS6	Species7
BS7	Species7
BS8	Species7
TtTUS9	Species8
TtTUS3	Species8
TtTUS4	Species8
TtTUS14	Species8

Any help is much appreciated. Thank you!

**Comment by millanek** [comment]
Hi...
Sorry, I was overwhelmed with home-schooling my son and a deadline for a big review article, so didn't pay attention here.

I am not sure what is causing your problem, but if you haven't resolved it yet, then I suggest the best way is to email me your input files (for the VCF, the first 10,000 lines is enough), and I look into it for you.

Best wishes
Milan

**Comment by ethering** [comment]
I've had this error a few times. It might be that your species names are not separated by commas. Dsuite doesn't like whitespace in the treefile, so I wonder if the treefile is parsed by commas, so going straight into the bracket causes an error.
Try:
`(Outgroup,((Species1,(Species2)),(Species4,(Species5,Species6,Species8,Species7,Species3))));`

**Comment by millanek** [comment]
Hello

Indeed, the tree file parsing uses commas, so they are needed. Also, the tree must be strictly bifurcating for Fbranch. I see that the tree from MarineBio5 is not bifurcating. There are five species together on one leaf: (Species5,Species6,Species8,Species7,Species3). That would probably cause trouble too.

Whitespace in taxon names should be parsed fine now with the latest update (r38). Also dashes "-" are fine now.
