### ISSUE TITLE
Can not make a Dsuite

### ISSUE THREAD

**Issue by SergeyNikonov** [millanek/Dsuite#16]
Hello,
I can not make a Dsuite to compile properly.
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
g++ -c -std=c++11 Dsuite.cpp -o Build/Dsuite.o
In file included from Dsuite.cpp:10:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from Dsuite.cpp:10:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -c -std=c++11 Dsuite_utils.cpp -o Build/Dsuite_utils.o
In file included from Dsuite_utils.cpp:9:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from Dsuite_utils.cpp:9:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -c -std=c++11 D.cpp -o Build/D.o
In file included from D.h:12,
                 from D.cpp:9:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from D.h:12,
                 from D.cpp:9:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -c -std=c++11 gzstream.cpp -o Build/gzstream.o
g++ -c -std=c++11 Dmin.cpp -o Build/Dmin.o
In file included from Dmin.h:11,
                 from Dmin.cpp:9:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from Dmin.h:11,
                 from Dmin.cpp:9:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -c -std=c++11 Dmin_combine.cpp -o Build/Dmin_combine.o
In file included from Dmin_combine.h:12,
                 from Dmin_combine.cpp:9:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from Dmin_combine.h:12,
                 from Dmin_combine.cpp:9:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -c -std=c++11 Dsuite_fBranch.cpp -o Build/Dsuite_fBranch.o
In file included from Dsuite_fBranch.h:13,
                 from Dsuite_fBranch.cpp:9:
Dsuite_utils.h:75:88: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   75 | er> double median(RandAccessIter begin, RandAccessIter end) throw(median_of_empty_list_exception) {
      |                                                             ^~~~~

In file included from Dsuite_fBranch.h:13,
                 from Dsuite_fBranch.cpp:9:
Dsuite_utils.h:381:29: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  381 |     void calculateFinalDs() throw(const char*) {
      |                             ^~~~~
g++ -std=c++11 Build/Dsuite.o Build/Dsuite_utils.o Build/D.o Build/gzstream.o Build/Dmin.o Build/Dmin_combine.o Build/Dsuite_fBranch.o -o Build/Dsuite -lz

It only creates *.o files

What can I do?

Thanks

**Comment by millanek** [comment]
Sorry, I am not sure. In your post I see only 'warnings', and these should not be a reason for the code not to compile.
