### ISSUE TITLE
Urgent help: Installing problem

### ISSUE THREAD

**Issue by foala** [millanek/Dsuite#18]
Hello,
Thank you for this promising tool. I am excited to get all the D-statistics with vcf file alone.

I have been trying to compile it on a conda environment for **two weeks** now, but this kept failing.
I installed gcc 4.9 (https://anaconda.org/serge-sans-paille/gcc_49) on a new condo environment, but I keep getting this error
`./Build/Dsuite: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /Build/Dsuite).`
I tried installing newer gcc versions (5.5, 6, 7.2) all via conda, but I keep getting the same error.
When I checked
`strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX`
I got
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
Can you please assist.
Your urgent response is highly appreciated.
Thanks,

**Comment by wheatwill** [comment]
I got the same problem after I install GCC (version 10.1.0 ), My systerm GCC version is 4.8.0 )
--------------------------------------------------------------------------------------------
[ligw@node100 gcc-10.1.0]$  strings /home/ligw/software/gcc-10.1.0/lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.6
GLIBC_2.4
GLIBC_2.16
GLIBC_2.17
GLIBC_2.3.2
-----------------------------------------------------------------------------------------
[ligw@node100 gcc-10.1.0]$  strings /lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
---------------------------------------------------------------------------------

**Comment by wheatwill** [comment]
I had fixed this issue. I add the new version gcc library into the LD_LIBRARY_PATH in the upset of the systerm gcc library. The fellow is my setting.
-----------------------------------------------------------------------------------------------
LD_LIBRARY_PATH=/home/ligw/software/gcc-10.1.0/lib64:/home/ligw/software/gcc-10.1.0:/home/ligw/software/mpc-1.0.2/lib:/home/ligw/software/gmp-5.0.1/lib:/home/ligw/software/mpfr-3.1.2/lib:/home/ligw/lib/isl/lib:/home/ligw/lib/isl:$LD_LIBRARY_PATH:/public/home/ligw/lib:/public/home/ligw/lib64
export LD_LIBRARY_PATH
