### ISSUE TITLE
Dsuite installation

### ISSUE THREAD

**Issue by apollomarco** [millanek/Dsuite#2]
Dear Milla,

Encountered a problem while installing D-suite in our Linux server. Here is the error:

Dmin_combine.cpp:139:30: error: use of undeclared identifier 'isnan'
                        if (!isnan(thisBBAA_localD)) BBAA_local_Ds.push_back(thisBBAA_localD);
                             ^
Dmin_combine.cpp:142:30: error: use of undeclared identifier 'isnan'
                        if (!isnan(thisBABA_localD)) BABA_local_Ds.push_back(thisBABA_localD);
                             ^
Dmin_combine.cpp:145:30: error: use of undeclared identifier 'isnan'
                        if (!isnan(thisABBA_localD)) ABBA_local_Ds.push_back(thisABBA_localD);
                             ^
3 errors generated.
Makefile:13: recipe for target 'Build/Dmin_combine.o' failed
make: *** [Build/Dmin_combine.o] Error 1

I have gcc ver. 5.4 and clang ver. 3.8. installed in our network. What do you think is the problem?

Thanks!

Apollo

**Comment by liufy11** [comment]
the following URL offers the solution
http://www.it1352.com/468819.html
or you can simply change the "isnan" to "std:isnan" in Dmin_combine.cpp
then make

**Comment by millanek** [comment]
Thanks Apollo

Looks like your compiler did not like my use of the (admittedly deprecated) math.h header for the maths functions. 

I now switched to using the newer <cmath> header and the std:: namespace for maths functions, which seems to be the more "proper" way to do things in modern C++. So hopefully this issue should be resolved and the program should compile for you. 

Just do "git pull" to get the latest code, and then try the "make" command again.

Kind regards
Milan

**Comment by apollomarco** [comment]
Dear Milan,

Sorry for the late update. I was away for several courses and I just back read through my emails. Unfortunately, there is some glitch in our server so I will try what you have suggested once it was fixed.

Thank you very much for your help! I’ll keep you updated.

All the best,

Apollo
