### ISSUE TITLE
WARNING: Fewer than five blocks to calculate jackknife!! 

### ISSUE THREAD

**Issue by LeoYYXX** [millanek/Dsuite#21]
Could not calculate p-values for the trio: Species2 Species3 Species4
it looks like there aren't enough ABBA-BABA informative variants for this trio.

What does it mean?

**Comment by millanek** [comment]
Hi Leo 
Not sure what you are asking... the error message seems pretty clear to me.
I suggest you get the latest version of Dsuite (e.g. with git pull) where Dtrios sets the jackknife window size automatically. Using the latest version should prevent this error message from appearing.

Milan

**Comment by LeoYYXX** [comment]
Thanks to your reply. I changed another vcf and it works. I think it was my vcf that went wrong. thank you for your wonderful software.


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by wuyh0328** [comment]
> anek/Dsuite <Dsuite@noreply.github.com> CC:LeoYYXX <liaoxiliang@aliyun.com>, Author <author@noreply.github.com> Subject:Re: [millanek/Dsuite] WARNING: Fewer than five blocks to calculate jackkn

Hello, what is the size of the JKwindow you set? Mine had the same error.THANKS!
