### ISSUE TITLE
Question about the plot of F-branch

### ISSUE THREAD

**Issue by silvewheat** [millanek/Dsuite#25]
Hello, 
I have some question about the plot of F-branch.
1. There are some grey cell in the heatmap, what are they represent? What is the difference between grey cell and white cell?
2. Some branchs in Y-axis are show in dotted line and without branch name. Are they subsampled from the real branch and used to calculate fG? If they are, which real branch are they sampled from?
For example, in the following plot, is the branch 6 sampled from p and q? The branch 5 is sampled from o? The branch 4 is sampled from n? The branch 3 is sampled from m? What about branch 2?  Sampled from m, n, o, p, and q? And how about branch 1?
![fbranch](https://user-images.githubusercontent.com/19344997/91449253-78174a80-e8ad-11ea-9400-2156ebc75867.png)

**Comment by millanek** [comment]
Hello

Just very briefly:
1) The grey cells in the heatmap correspond to combinations of branches and populations for which the Fbranch cannot be calculated given the topology of the tree.
2) The dotted lines point to internal branches in the tree. So branch 6 is the ancestral branch of p and q.

We have an expanded manuscript with more detail about Dsuite, and about Fbranch in particular, under review, so I hope you will be able to read that soon. 

Kind regards
Milan

**Comment by xiekunwhy** [comment]
Hi, how to plot those gene flow arrows?
