### ISSUE TITLE
ERROR: The tree string could not be parsed correctly!

### ISSUE THREAD

**Issue by Chenghong412** [millanek/Dsuite#28]
Hello,
 When I use Dsuite (Version: 0.4 r34) Fbranch, the tree can not be parsed correctly. 
![dsuite_error](https://user-images.githubusercontent.com/30622127/95702605-6502e300-0c7f-11eb-9fd3-e69ac48af50d.png)
The input tree was as follows. Is this error due to the tree topology? What should I do to fix this error?
(Outgroup,((CA_BIG,CA_THIN),(KG_AGL,(IR_URI,(IR_MOU,(((EU-MOU,(EU-OA,(DE-MRN,AU-MRN))),AM-OA),(((IR-OA,(((((((CN-TAN,(CN-YNS,(CN-TIB,CN-OLA))),CN-STH),CN-HU),CN-WZM),CN_CLB),CN-BYK),EA-OA)),TR-OA),AF-OA)))))));

Best,
Hong Cheng

**Comment by millanek** [comment]
Dear Hong Cheng

Please update to the latest version (r38). Your tree should parse fine now.

Best wishes
Milan

**Comment by Ying-Guo** [comment]
Hi Milan,

I have the same issue, the name in the tree file do not have any space or  "_", only characters. 

ERROR: The tree string could not be parsed correctly! The remaining unparsed tree string is:
(Outgroup,internalNode2X,internalNode38X);

And its the newest version "Version: 0.4 r38".

If I removed the Outgroup from the tree file, it works but for the next step plotting, it has issue with "KeyError: "['Outgroup'] not found in axis"". The "_fbranch.txt " file starts with branch b2 without the Outgroup.

Could you please help me fix the bug?
Best,
Ying

**Comment by millanek** [comment]
Hi Ying

That's interesting. I will be happy to find a fix for you. The best way for me to start finding the error is if you would be willing to email me the tree file and also the Dtrios "_tree.txt" output. Would that be OK?

Best wishes
Milan

**Comment by millanek** [comment]
This has now been resolved. The error appeared because Ying's tree was unrooted. I added a note to the documentation that the tree for Fbranch must be rooted with the Outgroup.
