### ISSUE TITLE
Dsuit install error

### ISSUE THREAD

**Issue by congzhouczcz** [millanek/Dsuite#3]
Dear milla,
when install Dsuit in my Linux, the error like this:
Dmin.cpp: In function ‘int DminMain(int, char**)’:
Dmin.cpp:83:56: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [1])’
         line = std::regex_replace(line,branchLengths,"");
                                                        ^
I think it may be the difference between VS and g++, ''It's illegal to bind a non-const reference to a temporary. Historically however VS compilers have been less strict about this.''
How can I change this line:
    'line = std::regex_replace(line,branchLengths,"") '  ?
Sorry for my ignorance about c++.
Thanks,
Cong

**Comment by millanek** [comment]
Hi Cong

I think it is most likely because your standard library does not have any implementation of the regex (regular expression) functions. I don't know which version of VS started supporting regex; in gcc it is version 4.9 and newer. Please let us know if you figure it out.

Cheers
Milan
