### ISSUE TITLE
P1 and P2 are inverted across different combination.

### ISSUE THREAD

**Issue by nicotel** [millanek/Dsuite#30]
Dear millanek,

Thanks for such useful software.
I have one question concerning the outputs.

I am using Dtrios and forcing the output using a newick file in input which is organized as follow:   
(Outgroup,(Species1,(Species2,Species3)));

The script runs using a for cycle in which every iteration replace Specie2 whit a new candidate group.
For example:
(Outgroup,(Species1,(Species2A,Species3)));
(Outgroup,(Species1,(Species2B,Species3)));
(Outgroup,(Species1,(Species2C,Species3)));

Nevertheless, in the outputs in "__tree.txt" sometimes Species2 and Species3 are inverted. 

For example: 

P1 | P2 | P3 | Dstatistic | Z-score | p-value | f4-ratio | BBAA | ABBA | BABA
Species3 | Species2B | Species1 | 0.143933 | 7.99989 | 6.23E-16 | 0.0196811 | 12149.8 | 1063 | 795.5
Species2A | Species3 | Species1 | 0.147353 | 7.04704 | 9.14E-13 | 0.0136954 | 11767.1 | 688.125 | 511.375

This leads to a difficult comparison between the data because for example in the ABBA field (Species3 | Species2B | Species1) the B alleles correspond to the alternative alleles in Species**2B** | Species**1** while in (Species2A | Species3 | Species1) the B alleles (under ABBA) correspond to the alternative alleles in Species**3** | Species**1** . 

So I was wondering does exist a way to force the calculation of the output keeping the populations fixed so that Species3 is always P2 ? 

Thank you for your time, 
Hope the question is clear.

Best regards,

Nicolò Tellini

**Comment by millanek** [comment]
Hi Nicolò

The comparison is simple - to flip your species 2 and species 3 (P1 and P2), simply flip ABBA <-> BABA and D = -D.

Best wishes
Milan
