### ISSUE TITLE
Defining the quartets/trios

### ISSUE THREAD

**Issue by XueyunF** [millanek/Dsuite#31]
Dear Dr. Milan Malinsky

I encountered a problem when calculating all the possible D statistics for a large set of populations (45 ingroups and 1 outgroup). After running Dtrios with all the 46 populations, I got 14190 lines of output. So the number of trios is defined as choose(45,3), as the outgroup is fixed. 

However, it is not a complete combination of trios. There should be 45 different choices for P3, 44 for P2 and 43 for P1. Thus the total number of possible trios shall be 45*44*43 = 85140. I am not sure if this is the correct way of generating all the possible trios, could you give some suggestions?

Best,
Xueyun

**Comment by millanek** [comment]
Dear Xueyun

I think you have confused combinations and permutations. They are two different concepts. The number of combinations is indeed choose(45,3)= 14190.
See: https://en.wikipedia.org/wiki/Combination

Milan
