### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by nicolo-tellini** [millanek/Dsuite#36]
Dear Millanek, 

A question about the data on the vcf. 
How are missing info about the genotype handled by the software?

For example: 
In my vcf I have positions such as this :

chr1  123385	.	G	A	267.58	.	AC1=0;AC=2;AF1=0;AN=26;DP4=1223,1123,35,10;DP=2521;FQ=-137.987;MQ0F=0;MQ=60;MQSB=1;SF=0,1,2,3,4,5,6,7,8,9,11,12,13;SGB=-0.693147;VDB=0.110291	GT:SP:AD:ADF:PL:DP:ADR	0/0:0:37:21:.,.,.:37:16	0/0:0:235:112:.,.,.:235:123	0/0:0:197:95:.,.,.:197:102	0/0:0:265:150:.,.,.:265:115	0/0:0:199:105:.,.,.:199:94	0/0:0:106:63:.,.,.:106:43	0/0:0:89:44:.,.,.:89:45	0/0:0:182:98:.,.,.:182:84	0/0:0:197:100:.,.,.:197:97	0/0:0:242:131:.,.,.:242:111	.	0/0:0:294:153:.,.,.:294:141	1/1:0:0,45:0,35:255,135,0:45:0,10	0/0:0:303:151:.,.,.:303:152

the fourth genotype from the end is a dot (.), this position is missing against one sample. Is the position chr1 123385 going to be used for the measure of the D statistics? or it is going to be discarded ?

Thanks,

Best Regards, 

Nicolò Tellini

**Comment by millanek** [comment]
Hi Nicolo

Sites with some missing data are still used. If all individuals of a species/population have missing data then the site is not used for the trios where this population/species occurs.

Hope this helps
Milan

PS: As a site note, isn't a more common way to denote missing data for a diploid individual to have two dots and a slash in the middle ./. rather than a single dot?

**Comment by nicolo-tellini** [comment]
Hello millanek,

thank you for the reply. 

The ./. is a typical output of a multisample calling so when you run as input several samples with the same samtools/bcftools command. In this case I run the sample one by one and then I merged the vcfs with vcf-merge that by default use the dot. 

should I replace the single . with ./. for the correct use of Dsuite trios ?  

Best,

Nicolò

**Comment by dzaccook** [comment]
Hi Milan,
You say "Sites with some missing data are still used", what is the ratio of missing data? and is it for a species/population or for all trios?
Best Regards,
