### ISSUE TITLE
pool-seq

### ISSUE THREAD

**Issue by Vicbuz** [millanek/Dsuite#43]
Hello,

I was wondering if there was anyway to incorporate pool-seq data into the programme? by using allele counts from the AD field in vcfs resulting from pool-seq? I am aware of the new Poolfstat but that doesn't have the ability to implement f_dM for finding specific introgressed loci using windows across the genome.

**Comment by Vicbuz** [comment]
Excellent! I have a code that grabs allele frequencies to create a matrix but performing in the package straight from vcf would be very useful to many people I think. Its common to use supporting reads to create pool counts to represent allele frequencies from the AD field created by GATK. Happy to send an example data, set. Could you supply me with an email? I can't seem to attach it here. 

Best,

Vic

**Comment by millanek** [comment]
Hi Vic

This functionality has now been added to Dsuite Dtrios. See the -p or --pool-seq option.

Hope you will find this useful. Please let me know if it works for you and if you have any questions

Best wishes
Milan
