### ISSUE TITLE
How do I download example files

### ISSUE THREAD

**Issue by m-rq** [millanek/Dsuite#57]
The example files could not be downloaded.
I want to download the example files Malawi cichlid data used in the manuscript: [VCF file](http://cichlid.gurdon.cam.ac.uk/Malinsky_et_al_2018_LakeMalawiCichlids_scaffold_0.vcf.gz); [SETS.txt file](http://cichlid.gurdon.cam.ac.uk/sets.txt)
Simulated 20-species data used in the manuscript: [VCF file](http://cichlid.gurdon.cam.ac.uk/sim_dsuite_20species_5gene-flowF_all.vcf.gz); [SETS.txt file](http://cichlid.gurdon.cam.ac.uk/s20_sets.txt); [TREE_FILE.nwk](http://cichlid.gurdon.cam.ac.uk/sim_input_tree_raw_dsuite_20species_5gene-flow_1.newick) (input tree),
which are mentioned in [README.md](https://github.com/millanek/Dsuite#readme).

However, these files cannot be downloaded. How do I download these files?

**Comment by RezaFahi** [comment]
try this link

https://github.com/millanek/tutorials/tree/master/analysis_of_introgression_with_snp_data/data
