### ISSUE TITLE
Dsuite: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 

### ISSUE THREAD

**Issue by Yung-Chien** [millanek/Dsuite#6]
Hi @millanek ,
When I try to run the program ./Dsuite , I get this report:

./Dsuite: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./Dsuite)

so how could I fix this problem, thanks in advance.

Best Regards,
Yung-Chien

**Comment by Yung-Chien** [comment]
And if I choose to remake this file, how could use my own zlib without root right? or the other way to make Dsuite to recognize my own lib instead of using system-provided gcc because it's version is too low. Thanks very much.

Yung-Chien

**Comment by MarineBio5** [comment]
Make sure to load a recent version of GCC

_module load gcc/4.9.1_
