### ISSUE TITLE
Make error during installation

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [millanek/Dsuite#61]
I am trying to install Dsuite in my home directory on my University's Cluster (x86_64-redhat-linux) and I run into the make error attached (lots of undefined references). I have downloaded the current Version of Dsuite and attempted the installation using the current version of gcc (12.0.3), as well as gcc 4.9. and gcc 10.3, which were each installed into a conda environment. I can't really identity the problem and would be grateful for your help.

Thank you 

[make-error.txt](https://github.com/millanek/Dsuite/files/9746683/make-error.txt)

**Comment by millanek** [comment]
I am sorry Claudia but I don't know. I just now compiled the latest code on Ubuntu Linux (gcc version 11.1.0) and also on my Mac (clang version 13.1.6). I suggest you contact your local IT admin.

All the best
Milan
