### ISSUE TITLE
Mixed sample size

### ISSUE THREAD

**Issue by Jolvii85** [millanek/Dsuite#62]
Hi,

I am analyzing a dataset with a mixed sample size, i.e. most species/groups have only 1 individual, and only 4 groups have multi-samples (6-8), is it ok to use such a dataset to perform Dsuite analysis? 

And second question: if I have many species but all samples are haploid,  is it ok to use such a dataset to run Dsuite?

Thank you!

**Comment by feilchenfeldt** [comment]
Hello @Jolvii85 ,

Having mixed sample size in different populations is not a problem.

In principle the method should also work for haploid individuals, only the f4ratio cannot be estimated for populations with a single haploid sample. I am not sure whether Dsuite would handle that nicely or not, but Dsuite has a --ploidy option to set the ploidy.
That said, if they are truly haploid, do you expect to see introgression?

Best wishes,
Hannes

**Comment by millanek** [comment]
I agree with Hannes' reply.

Best wishes
Milan
