### ISSUE TITLE
Dsuite Dtrios creates no output files when --out-prefix points to a non-existing directory

### ISSUE THREAD

**Issue by feilchenfeldt** [millanek/Dsuite#64]
Hi Milan,

I think the following would be very quick to fix:

Current behaviour:
When `Dsuite Dtrios` is run using `--out-prefix a/test` but the directory `a` does not exist, then Dsuite runs normally without any error message, but it just does not produce the output files.

Expected behaviour:
Either: Check in the beginning whether the directories used in `--out-prefix` exist and throw an error if not.
Or: Create the directories.

Thanks,
Hannes

**Comment by millanek** [comment]
Hi Hannes
Sure, I did this today ;). Please do test and let me know.

Milan
