### ISSUE TITLE
use Dquartets still need 'Outgroup'

### ISSUE THREAD

**Issue by yangfty** [millanek/Dsuite#66]
I want to use Dsuite Dquartets to try to find all possibilities, but I provided 8 species and the program keeps reporting an error indicating that Outgroup is required (ERROR: The file test2.txt needs to specify the "Outgroup"), I'm not sure what's wrong, I see that the help indicates that Outgroup is not required in Dsuite Dquartets.

test2.txt ( | equals tab) :
A-1 | Species1
B-2 | Species2
C-3 | Species3
C-4 | Species3
C-5 | Species3
C-6 | Species3
C-7 | Species3
C-8 | Species3
D-9 | Species4
D-10 | Species4
D-11 | Species4
D-12 | Species4
D-13 | Species4
D-14 | Species4
E-15 | Species5
E-16 | Species5
E-17 | Species5
E-18 | Species5
E-19 | Species5
E-20 | Species5
E-21 | Species5
F-22 | Species6
F-23 | Species6
F-24 | Species6
F-25 | Species6
F-26 | Species6
F-27 | Species6
G-28 | Species7
G-29 | Species7
G-30 | Species7
G-31 | Species7
G-32 | Species7
G-33 | Species7
H-34 | Species8
H-35 | Species8
H-36 | Species8
H-37 | Species8
H-38 | Species8
H-39 | Species8

**Comment by millanek** [comment]
Hi [yangfty](https://github.com/yangfty)

This should be fixed now. Thanks for reporting.

Milan
