### ISSUE TITLE
Dtrios error in calculating f4-ratio when using genotype probabilities, but not with genotype calls

### ISSUE THREAD

**Issue by zjnolen** [millanek/Dsuite#67]
I am trying to use Dtrios (r50) on a dataset with relatively low depth, so am interested in using the `-g / --use-genotype-probabilities` option for calculating allele frequencies, since we are using likelihood based analyses for the rest of our workflow. Using the same VCF without the `-g` option works successfully, however, once `-g` is added, I receive an error:

```
> ./Build/Dsuite Dtrios -g -o dsuite_test test.8000.vcf SETS.txt
There are 8 sets (populations/species) excluding the Outgroup
Going to calculate D and f4-ratio values for 56 trios
Done permutations
The VCF contains 5242 variants
Going to use block size of 261 variants to get 20 Jackknife blocks
Assertion failed: (p_S3a >= 0), function DminMain, file Dmin.cpp, line 426.
[1]    63164 abort      ./Build/Dsuite Dtrios -g -o dsuite_test test.8000.vcf SETS.txt
```

Looking at the [line mentioned in Dmin.cpp](https://github.com/millanek/Dsuite/blob/76a56a5a3a665d1de524f16eb4f9b74234f925a8/Dmin.cpp#L426) and seeing it was a part of the Fstats section, I added `--no-f4-ratio` to confirm if it was related and the tool ran successfully:

```
> ./Build/Dsuite Dtrios -g --no-f4-ratio -o dsuite_test test.8000.vcf SETS.txt
There are 8 sets (populations/species) excluding the Outgroup
Going to calculate D values for 56 trios
Done permutations
The VCF contains 5242 variants
Going to use block size of 261 variants to get 20 Jackknife blocks
Done processing VCF. Preparing output files...
```

I've also tested this on a VCF for another dataset that was produced through a different variant caller and the same behavior occurs, though it is not always `p_S3a` in the error, it can also be `p_S2a`. I've tested a few previous versions and it seems anything from r44 onward causes this error for me.

Thanks for any help on this!

Best,
Zach

**Comment by rtfcoimbra** [comment]
I'm running into the exact same issue...

```
$ Dsuite Dtrios -c -g -k 100 -o dsuite -n oag-m1 -t oag.m1.r2.rooted.nwk snps.sampled.vcf sample_sets.txt
There are 14 sets (populations/species) excluding the Outgroup
Going to calculate D and f4-ratio values for 364 trios
Done permutations
The VCF contains 462697 variants
Going to use block size of 4625 variants to get 100 Jackknife blocks
Dsuite: Dmin.cpp:426: int DminMain(int, char**): Assertion `p_S3a >= 0' failed.
Aborted (core dumped)
```

**Comment by millanek** [comment]
Hi Zach and [rtfcoimbra](https://github.com/rtfcoimbra)

Maybe this is something I should look into. I would need from you a dataset that I can use to reproduce the error. Would you be willing to share this with me?

All the best
Milan

**Comment by rtfcoimbra** [comment]
Hi @millanek,

Thank you for your quick response.

Sure. Here is a smaller version of the VCF file, the sample sets file, and tree file that I used with the previous command.
[test_files.tar.gz](https://github.com/millanek/Dsuite/files/11413603/test_files.tar.gz)

Best,
Raphael

**Comment by rtfcoimbra** [comment]
Hi Milan,

I've just tested the update and it worked with no issues now.

Thank you for the fix!

Best,
Raphael
