### ISSUE TITLE
How to calculate Z-score using Dtrios' output?

### ISSUE THREAD

**Issue by silvewheat** [millanek/Dsuite#7]
Hello Milan,

   As most published papers using Z-score (>3 or >2) to determine which trio is significant, I wonder if I can get the Z-score from the output file of Dtrios?
   Is the "combine_stderr.txt" contains all the D-statistics calculated using Jackknife block under the arrangement that same with "combine.txt"?  So, can I use these data to calculate Z-score?

**Comment by millanek** [comment]
Hi silvewheat

Dtrios and DtriosCombine output the p-values for each trio. If you prefer the Zscores you can calculate them from the p-values. For example in R: 
`Zscore <- qnorm(pValue, lower.tail=F)`

Milan
