### ISSUE TITLE
Dinvestigate issue: D.cpp:80: void doAbbaBaba(): Assertion `threePops.size() == 3' failed

### ISSUE THREAD

**Issue by drew-olson-tmru** [millanek/Dsuite#90]
Hi, I am having issues with Dsuite investigate. It seems like this should be straightforward to use, but I'm running into this issue: 

There are 3 sets (populations/species) excluding the Outgroup
Dsuite: D.cpp:80: void doAbbaBaba(): Assertion `threePops.size() == 3' failed.
Aborted (core dumped)

My command is:
$DSUITE Dinvestigate $VCFFILE $SETSTXT $TRIOSTEXT

[dsuite_trios.txt](https://github.com/millanek/Dsuite/files/13978950/dsuite_trios.txt)
[dsuite.sets.txt](https://github.com/millanek/Dsuite/files/13978951/dsuite.sets.txt)

I can include parts of the VCF if needed. 

I have been following this tutorial (https://github.com/mmatschiner/tutorials/blob/master/analysis_of_introgression_with_snp_data/README.md#simulation), however, I don't see why my script is not running in comparison to the tutorial. 

Can someone please help me with this? 

Thank you!

**Comment by shangshanzhizhe** [comment]
Popping out for similar experience.

Removing the last empty line in the trio file would work.

**Comment by drew-olson-tmru** [comment]
> Popping out for similar experience.
> 
> Removing the last empty line in the trio file would work.

Thanks for the suggestion. I removed the empty line, but that did not solve the issue. This VCF file was generated from Minigraph Cactus pangenome using long-reads and vg girraffe which aligned short-reads to the pangenome to generate vcfs. I'm wondering if the formatting might be the issue here. These were then sorted, indexed, and merged. I saw another post which had a compilation issue, but I ran tutorial data through the software and it worked fine. I am adding in a subset of the vcf file here. Hopefully it is a simple formatting issue. 
[head_5000_complete_fus.vcf.gz](https://github.com/millanek/Dsuite/files/14411004/head_5000_complete_fus.vcf.gz)

**Comment by drew-olson-tmru** [comment]
That did not work for me. But now I am getting this:

There are 3 sets (populations/species) excluding the Outgroup
/builddir/build/BUILD/gcc-11.4.1-20230605/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1040: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
